"""Transport and host adapters for NNRP integrations."""

from nnrp.adapters.quic import (
    NNRP_ALPN,
    NNRP_CURRENT_ALPN,
    NnrpQuicConnection,
    NnrpQuicConnectionClosedError,
    NnrpQuicError,
    NnrpQuicListener,
    NnrpQuicProtocolError,
    alpn_for_wire_format,
    connect_quic,
    create_quic_client_configuration,
    create_quic_server_configuration,
    serve_quic,
)
from nnrp.adapters.tcp import (
    NnrpTcpClientConfiguration,
    NnrpTcpConnection,
    NnrpTcpConnectionClosedError,
    NnrpTcpError,
    NnrpTcpListener,
    NnrpTcpProtocolError,
    NnrpTcpServerConfiguration,
    NnrpTcpUnsupportedOperationError,
    connect_tcp,
    create_tcp_client_configuration,
    create_tcp_server_configuration,
    serve_tcp,
)

__all__ = [
    "NNRP_ALPN",
    "NNRP_CURRENT_ALPN",
    "NnrpQuicConnectionClosedError",
    "NnrpQuicConnection",
    "NnrpQuicError",
    "NnrpQuicListener",
    "NnrpQuicProtocolError",
    "NnrpTcpClientConfiguration",
    "NnrpTcpConnection",
    "NnrpTcpConnectionClosedError",
    "NnrpTcpError",
    "NnrpTcpListener",
    "NnrpTcpProtocolError",
    "NnrpTcpServerConfiguration",
    "NnrpTcpUnsupportedOperationError",
    "alpn_for_wire_format",
    "connect_quic",
    "connect_tcp",
    "create_quic_client_configuration",
    "create_quic_server_configuration",
    "create_tcp_client_configuration",
    "create_tcp_server_configuration",
    "serve_quic",
    "serve_tcp",
]
